# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d50fd4f20bc4813fdc1d1d958915354ee62636641f881706709c7ca787e40b44b36204f8f8942e3e04ac74cced6a01883a545420997effb328ef8809aac839fc

test:
  secret_key_base: da94c2e49bf01feef1a282f7ec115d3f1b449cbdd243ad63673ec2644d35abebc018045d38ef52233af5f44cce7145fae5c6e92b9c41288424756841b412fc81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
